# SPDX-FileCopyrightText: 2026 Vladimir Rusinov <vladimir.rusinov@gmail.com>
# SPDX-License-Identifier: Apache-2.0

[files]
extend-exclude = ["third_party/submodules/*/*"]

[default.extend-words]
# False-positives in some version strings
# TODO: try removing
afe = "afe"
hge = "hge"
ba = "ba"
# python-keyring seems to use this.
# TODO: remove after removing python-keyring
Uncrypted = "Uncrypted"
Crypted = "Crypted"
